/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gamemode = string;
export interface Player {
  'id' : PlayerId,
  'region' : string,
  'name' : string,
  'createdAt' : Time,
  'tier' : Tier,
  'notes' : string,
  'discordUsername' : string,
  'gamemode' : Gamemode,
}
export interface PlayerDTO {
  'id' : PlayerId,
  'region' : string,
  'name' : string,
  'createdAt' : Time,
  'tier' : Tier,
  'notes' : string,
  'discordUsername' : string,
  'gamemode' : Gamemode,
}
export type PlayerId = bigint;
export interface PlayerSubmission {
  'id' : SubmissionId,
  'region' : string,
  'name' : string,
  'submittedAt' : Time,
  'discordUsername' : string,
  'gamemode' : Gamemode,
  'submissionTier' : string,
}
export type SubmissionId = bigint;
export type Tier = { 'HT1' : null } |
  { 'HT2' : null } |
  { 'HT3' : null } |
  { 'HT4' : null } |
  { 'HT5' : null } |
  { 'LT1' : null } |
  { 'LT2' : null } |
  { 'LT3' : null } |
  { 'LT4' : null } |
  { 'LT5' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveSubmission' : ActorMethod<[SubmissionId, Tier, string], Player>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlayer' : ActorMethod<[PlayerDTO], Player>,
  'deletePlayer' : ActorMethod<[PlayerId], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingSubmissions' : ActorMethod<[], Array<PlayerSubmission>>,
  'getPlayersByGamemode' : ActorMethod<[Gamemode], Array<Player>>,
  'getPlayersByName' : ActorMethod<[string], Array<Player>>,
  'getPlayersByRegion' : ActorMethod<[string], Array<Player>>,
  'getPlayersByTier' : ActorMethod<[Tier], Array<Player>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectSubmission' : ActorMethod<[SubmissionId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPlayer' : ActorMethod<[string, string, string, Gamemode, string], undefined>,
  'updatePlayer' : ActorMethod<[PlayerId, PlayerDTO], Player>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];