/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const Tier = IDL.Variant({
  'HT1' : IDL.Null,
  'HT2' : IDL.Null,
  'HT3' : IDL.Null,
  'HT4' : IDL.Null,
  'HT5' : IDL.Null,
  'LT1' : IDL.Null,
  'LT2' : IDL.Null,
  'LT3' : IDL.Null,
  'LT4' : IDL.Null,
  'LT5' : IDL.Null,
});
export const PlayerId = IDL.Nat;
export const Time = IDL.Int;
export const Gamemode = IDL.Text;
export const Player = IDL.Record({
  'id' : PlayerId,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tier' : Tier,
  'notes' : IDL.Text,
  'discordUsername' : IDL.Text,
  'gamemode' : Gamemode,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerDTO = IDL.Record({
  'id' : PlayerId,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tier' : Tier,
  'notes' : IDL.Text,
  'discordUsername' : IDL.Text,
  'gamemode' : Gamemode,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlayerSubmission = IDL.Record({
  'id' : SubmissionId,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'discordUsername' : IDL.Text,
  'gamemode' : Gamemode,
  'submissionTier' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveSubmission' : IDL.Func([SubmissionId, Tier, IDL.Text], [Player], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlayer' : IDL.Func([PlayerDTO], [Player], []),
  'deletePlayer' : IDL.Func([PlayerId], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingSubmissions' : IDL.Func(
      [],
      [IDL.Vec(PlayerSubmission)],
      ['query'],
    ),
  'getPlayersByGamemode' : IDL.Func([Gamemode], [IDL.Vec(Player)], ['query']),
  'getPlayersByName' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'getPlayersByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectSubmission' : IDL.Func([SubmissionId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Gamemode, IDL.Text], [], []),
  'updatePlayer' : IDL.Func([PlayerId, PlayerDTO], [Player], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const Tier = IDL.Variant({
    'HT1' : IDL.Null,
    'HT2' : IDL.Null,
    'HT3' : IDL.Null,
    'HT4' : IDL.Null,
    'HT5' : IDL.Null,
    'LT1' : IDL.Null,
    'LT2' : IDL.Null,
    'LT3' : IDL.Null,
    'LT4' : IDL.Null,
    'LT5' : IDL.Null,
  });
  const PlayerId = IDL.Nat;
  const Time = IDL.Int;
  const Gamemode = IDL.Text;
  const Player = IDL.Record({
    'id' : PlayerId,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tier' : Tier,
    'notes' : IDL.Text,
    'discordUsername' : IDL.Text,
    'gamemode' : Gamemode,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerDTO = IDL.Record({
    'id' : PlayerId,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tier' : Tier,
    'notes' : IDL.Text,
    'discordUsername' : IDL.Text,
    'gamemode' : Gamemode,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlayerSubmission = IDL.Record({
    'id' : SubmissionId,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'discordUsername' : IDL.Text,
    'gamemode' : Gamemode,
    'submissionTier' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveSubmission' : IDL.Func(
        [SubmissionId, Tier, IDL.Text],
        [Player],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlayer' : IDL.Func([PlayerDTO], [Player], []),
    'deletePlayer' : IDL.Func([PlayerId], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(PlayerSubmission)],
        ['query'],
      ),
    'getPlayersByGamemode' : IDL.Func([Gamemode], [IDL.Vec(Player)], ['query']),
    'getPlayersByName' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
    'getPlayersByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
    'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectSubmission' : IDL.Func([SubmissionId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Gamemode, IDL.Text], [], []),
    'updatePlayer' : IDL.Func([PlayerId, PlayerDTO], [Player], []),
  });
};

export const init = ({ IDL }) => { return []; };