/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = bigint;
export interface PlayerDTO {
    id: PlayerId;
    region: string;
    name: string;
    createdAt: Time;
    tier: Tier;
    notes: string;
    discordUsername: string;
    gamemode: Gamemode;
}
export interface Player {
    id: PlayerId;
    region: string;
    name: string;
    createdAt: Time;
    tier: Tier;
    notes: string;
    discordUsername: string;
    gamemode: Gamemode;
}
export type Time = bigint;
export type Gamemode = string;
export interface PlayerSubmission {
    id: SubmissionId;
    region: string;
    name: string;
    submittedAt: Time;
    discordUsername: string;
    gamemode: Gamemode;
    submissionTier: string;
}
export interface UserProfile {
    name: string;
}
export type SubmissionId = bigint;
export enum Tier {
    HT1 = "HT1",
    HT2 = "HT2",
    HT3 = "HT3",
    HT4 = "HT4",
    HT5 = "HT5",
    LT1 = "LT1",
    LT2 = "LT2",
    LT3 = "LT3",
    LT4 = "LT4",
    LT5 = "LT5"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveSubmission(submissionId: SubmissionId, tier: Tier, notes: string): Promise<Player>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPlayer(player: PlayerDTO): Promise<Player>;
    deletePlayer(id: PlayerId): Promise<void>;
    getAllPlayers(): Promise<Array<Player>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPendingSubmissions(): Promise<Array<PlayerSubmission>>;
    getPlayersByGamemode(gamemode: Gamemode): Promise<Array<Player>>;
    getPlayersByName(searchTerm: string): Promise<Array<Player>>;
    getPlayersByRegion(region: string): Promise<Array<Player>>;
    getPlayersByTier(tier: Tier): Promise<Array<Player>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectSubmission(submissionId: SubmissionId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPlayer(name: string, discordUsername: string, region: string, gamemode: Gamemode, submissionTier: string): Promise<void>;
    updatePlayer(id: PlayerId, player: PlayerDTO): Promise<Player>;
}
import type { Gamemode as _Gamemode, Player as _Player, PlayerDTO as _PlayerDTO, PlayerId as _PlayerId, Tier as _Tier, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveSubmission(arg0: SubmissionId, arg1: Tier, arg2: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSubmission(arg0, to_candid_Tier_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSubmission(arg0, to_candid_Tier_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlayer(arg0: PlayerDTO): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(to_candid_PlayerDTO_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(to_candid_PlayerDTO_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePlayer(arg0: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSubmissions(): Promise<Array<PlayerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSubmissions();
            return result;
        }
    }
    async getPlayersByGamemode(arg0: Gamemode): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByGamemode(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByGamemode(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByName(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByName(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByName(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByRegion(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByRegion(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByRegion(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTier(arg0: Tier): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTier(to_candid_Tier_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTier(to_candid_Tier_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectSubmission(arg0: SubmissionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSubmission(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPlayer(arg0: string, arg1: string, arg2: string, arg3: Gamemode, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPlayer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPlayer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePlayer(arg0: PlayerId, arg1: PlayerDTO): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, to_candid_PlayerDTO_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, to_candid_PlayerDTO_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Player_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Tier_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tier): Tier {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    region: string;
    name: string;
    createdAt: _Time;
    tier: _Tier;
    notes: string;
    discordUsername: string;
    gamemode: _Gamemode;
}): {
    id: PlayerId;
    region: string;
    name: string;
    createdAt: Time;
    tier: Tier;
    notes: string;
    discordUsername: string;
    gamemode: Gamemode;
} {
    return {
        id: value.id,
        region: value.region,
        name: value.name,
        createdAt: value.createdAt,
        tier: from_candid_Tier_n5(_uploadFile, _downloadFile, value.tier),
        notes: value.notes,
        discordUsername: value.discordUsername,
        gamemode: value.gamemode
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HT1: null;
} | {
    HT2: null;
} | {
    HT3: null;
} | {
    HT4: null;
} | {
    HT5: null;
} | {
    LT1: null;
} | {
    LT2: null;
} | {
    LT3: null;
} | {
    LT4: null;
} | {
    LT5: null;
}): Tier {
    return "HT1" in value ? Tier.HT1 : "HT2" in value ? Tier.HT2 : "HT3" in value ? Tier.HT3 : "HT4" in value ? Tier.HT4 : "HT5" in value ? Tier.HT5 : "LT1" in value ? Tier.LT1 : "LT2" in value ? Tier.LT2 : "LT3" in value ? Tier.LT3 : "LT4" in value ? Tier.LT4 : "LT5" in value ? Tier.LT5 : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n3(_uploadFile, _downloadFile, x));
}
function to_candid_PlayerDTO_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerDTO): _PlayerDTO {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Tier_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): _Tier {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PlayerId;
    region: string;
    name: string;
    createdAt: Time;
    tier: Tier;
    notes: string;
    discordUsername: string;
    gamemode: Gamemode;
}): {
    id: _PlayerId;
    region: string;
    name: string;
    createdAt: _Time;
    tier: _Tier;
    notes: string;
    discordUsername: string;
    gamemode: _Gamemode;
} {
    return {
        id: value.id,
        region: value.region,
        name: value.name,
        createdAt: value.createdAt,
        tier: to_candid_Tier_n1(_uploadFile, _downloadFile, value.tier),
        notes: value.notes,
        discordUsername: value.discordUsername,
        gamemode: value.gamemode
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): {
    HT1: null;
} | {
    HT2: null;
} | {
    HT3: null;
} | {
    HT4: null;
} | {
    HT5: null;
} | {
    LT1: null;
} | {
    LT2: null;
} | {
    LT3: null;
} | {
    LT4: null;
} | {
    LT5: null;
} {
    return value == Tier.HT1 ? {
        HT1: null
    } : value == Tier.HT2 ? {
        HT2: null
    } : value == Tier.HT3 ? {
        HT3: null
    } : value == Tier.HT4 ? {
        HT4: null
    } : value == Tier.HT5 ? {
        HT5: null
    } : value == Tier.LT1 ? {
        LT1: null
    } : value == Tier.LT2 ? {
        LT2: null
    } : value == Tier.LT3 ? {
        LT3: null
    } : value == Tier.LT4 ? {
        LT4: null
    } : value == Tier.LT5 ? {
        LT5: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
